spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/riseschool?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  servlet:
    multipart:
      max-file-size: 10MB
mybatis:
  type-aliases-package: com.zhq.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true

