spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/riseschool?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
mybatis:
  type-aliases-package: com.zhq.pojo
  mapper-locations: classpath:/mapper/*.xml
