spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zxcvbnmA123
    url: jdbc:mysql://43.143.251.130:3306/question?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
mybatis:
  type-aliases-package: com.zhq.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
